nelmio_api_doc:
    documentation:
        info:
            title: Personal API
            description: This is Bizkaitarra personal API for personal proyects!
            version: 1.0.0
        paths:
            /api/exam/random-question/{applicationId}:

                get:
                    tags:
                        - Questions
                    description: Gets random exam providing the application id
                    sumary: Gets random exam providing the application id
                    parameters:
                        - in: path
                          name: applicationId
                          description: The application id
                          schema:
                              type: integer
                          required: true

                    responses:
                        '200':
                            description: The random question
                            schema:
                                $ref: '#definitions/Question'

                        '400':
                            description: Exams not found for Application ID {applicationId}
                            schema:
                                $ref: '#definitions/MessageResponse'
    models:
        names:
            Question:
                type: App\Exam\Domain\Question
                alias: Question

            MessageResponse:
                type: App\Shared\Domain\ExceptionResponse
                alias: MessageResponse


    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc


