security:
    password_hashers:
        App\Entity\CMSUser:
            algorithm: bcrypt
            cost: 4
    providers:
        app_user_provider:
            entity:
                class: App\Entity\CMSUser
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        quiz:
            security: true
            pattern: ^/quiz/
            lazy: true
            provider: app_user_provider
            custom_authenticator:
                    - App\Quiz\Infrastructure\Security\QuizUserAuthenticator
            logout:
                path: quiz_logout
                target: quiz_login
        main:
            security: true
#            pattern: ^/admin
            lazy: true
            provider: app_user_provider
            custom_authenticator:
                    - App\Admin\Infrastructure\Security\UserAuthenticator
            logout:
                path: admin_logout
                target: admin_login
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/quiz/play, roles: ROLE_QUIZ_USER }
        # - { path: ^/profile, roles: ROLE_USER }
    role_hierarchy:
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
        ROLE_ADMIN:
            - ROLE_QUIZ_USER