security:
    encoders:
        App\Entity\CMSUser:
            algorithm: bcrypt
            cost: 4
    providers:
        app_user_provider:
            entity:
                class: App\Entity\CMSUser
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Admin\Infrastructure\Security\UserAthenticatorAuthenticator
            logout:
                path: admin_logout
                target: admin_login
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
    role_hierarchy:
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
        ROLE_ADMIN:
            - ROLE_MANAGER