twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        "src/Admin/Infrastructure/Security/Templates": ~
        "src/Quiz/Infrastructure/Security/Templates": ~
        "src/Quiz/Infrastructure/Templates": ~
