admin:
  resource: '../src/Admin/Infrastructure/Routes/'
  type:     directory

exam-api:
  resource: '../src/Exam/Infrastructure/config/'
  type:     directory

swagger_ui:
  path: /api/doc
  controller: api_platform.swagger.action.ui